### PR TITLE
Fix issue with empty streams and multipart upload

### LINKED ISSUE #723: S3 uploadFileMultipart fails with empty input stream
WHAT IS WRONG

I use `uploadFileMultipart` to stream serialized database transactions to an S3 file. But, in the edge case that my DB query produces no results, I get the following error:

```
The XML you provided was not well-formed or did not validate against our published schema (Service: S3, Status Code: 400, Request ID: AXVBZSEAM6S8WJR7, Extended Request ID: luAacBiEwX5Xt8rpN2BvoNdaub+Q3phQTKal5flI0X5GedYxgIRONNXXp77V+6Yd7EZw0PL20t4=)
```

WHAT IS EXPECTED

I think that the most sensible thing in this case is to just create an empty file.

### PR DESCRIPTION
**Pull request by DamienOReilly**
This PR fixes #723 

It seems the AWS SDK V2 S3 API does not support uploading empty files via multipart upload. It also does not respond the user a meaningful error message.

Compare the following requests are that sent to S3 on completion of a multipart upload. The first is when data was uploaded, and the second when no data/empty file was attempted to be uploaded.
```
<?xml version="1.0" encoding="UTF-8"?>
<CompleteMultipartUpload
    xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Part>
        <ETag>&quot;a0b307dc9a2c8ef6297fbf0e07dd5758&quot;</ETag>
        <PartNumber>1</PartNumber>
    </Part>
</CompleteMultipartUpload>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<CompleteMultipartUpload
    xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
</CompleteMultipartUpload>
```

However the second request will result in a response from S3:
```
software.amazon.awssdk.services.s3.model.S3Exception: The XML you provided was not well-formed or did not validate against our published schema. (Service: S3, Status Code: 400, Request ID: 175977D7C4F19E5B, Extended Request ID: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)

	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
```

If we do not upload any multi parts to S3, we have no list of etag responses to "commit" via `S3AsyncClient.completeMultipartUpload`, which seems to be mandatory, hence the error. 

This PR introduces a a boolean `uploadEmptyFile` (set to `false` by default) on the `S3.uploadFileMultipart` method, to determine how to handle this scenario. If set to `false` (default) and no data has passed through the stream, it will gracefully abort the multi-part upload request. If set to true, and no data has passed through the stream, an empty file will be uploaded on completion. An `Option[ETag]` of `None` will be emitted on the stream if no file was uploaded, else a `Some(ETag)` will be emitted.

The change of the return type on the method `S3.uploadFileMultipart` from `Pipe[F, Byte, ETag]` to `Pipe[F, Byte, Option[ETag]]` would be considered a breaking change, albeit a small one, and not provide too much inconvenience for clients consuming the ETag.

### CODE REVIEW

**Comment by jeet23** [comment]
👍

File: fs2-aws-s3/src/main/scala/fs2/aws/s3/S3.scala [hunk 1]
```diff
@@ -106,20 +117,31 @@ object S3 {
             ).map(_.eTag() -> i.toInt)
           }
 
-        def completeUpload(uploadId: UploadId): Pipe[F, List[(PartETag, PartId)], ETag] =
+        def completeUpload(uploadId: UploadId): Pipe[F, List[(PartETag, PartId)], Option[ETag]] =
```
Comment (semenodm) [inline fs2-aws-s3/src/main/scala/fs2/aws/s3/S3.scala:120]: Can we consider a NonEmptyList of parts to complete and make the user handle this situation?

Comment (DamienOReilly) [reply fs2-aws-s3/src/main/scala/fs2/aws/s3/S3.scala:120]: Is your suggestion is that the return type would look something like:
`Pipe[F, List[(PartETag, PartId)], Option[NonEmptyList[(PartETag, PartId)]]`?

In the case of no data/empty file. There will be no parts at all to "complete". I'm not sure if its good to expect the user to "complete" the upload either. This could be a bigger breaking change to someone upgrading to a newer version of this library, and isn't aware that their uploads will be lost of they don't "complete" them. Let me know what you think.

**Comment by semenodm** [comment]
@DamienOReilly i'm ready to merge this. added some changes in your code.
